### ISSUE TITLE
utf8 problem

### ISSUE THREAD

**Issue by brownman** [froots/backbone-jasmine-examples#2]
ActiveRecord::UnknownAttributeError

unknown attribute: utf8
Rails.root: /home/user/JAVASCRIPT/backbone-jasmine-examples

Application Trace | Framework Trace | Full Trace
app/controllers/todos_controller.rb:47:in `create'
Request

Parameters:

{"utf8"=>"âœ“",
 "authenticity_token"=>"H4l56+sJt7RSFFia3NiO7OfMoFV17P15q71GcZyx11E=",
 "todo"=>{"title"=>"",
 "description"=>"",
 "priority"=>"",
 "position"=>""},
 "commit"=>"Create Todo"}

**Comment by mikegao** [comment]
the same error

**Comment by JesseBreuer** [comment]
Im getting the same error as well. mine shows a checkmark for the utf-8 value:

ActiveRecord::UnknownAttributeError

unknown attribute: utf8

Rails.root: C:/Users/jbreuer/Desktop/froots-backbone-jasmine
Application Trace | Framework Trace | Full Trace

app/controllers/todos_controller.rb:47:in `create'

Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"MeS/jtpP/fq4iWU875jNnX1Wqrajtcn13FYMgYQyY/Q=",
 "todo"=>{"title"=>"first",
 "description"=>"desc for first",
 "priority"=>"top",
 "position"=>"1"},
 "commit"=>"Create Todo"}

Show session dump

Show env dump
Response

Headers:

None
